name: Zbuduj i Wypchnij do GCP

on:
  push:
    branches: [ "main" ] # Uruchom tylko po wrzuceniu zmian na główną gałąź

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: 📥 Pobranie kodu repozytorium
      uses: actions/checkout@v3

    - name: 🔐 Logowanie do Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/362933082838/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-sa@project-900a854b-5db3-4235-aa5.iam.gserviceaccount.com'

    - name: 🐳 Konfiguracja Dockera
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

    - name: 🏗️ Zbudowanie i wypchnięcie obrazu
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        IMAGE_NAME=europe-central2-docker.pkg.dev/$PROJECT_ID/my-docker-repo/moja-aplikacja:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME